/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { prepareOCRInputFile } from "../../transfer";
import { detectHorizontalRuleBands,rowBandsFromRules,type CropBox } from "../../dynamic-rows";
import { parseHeaderlessRuntimeTsv,tsvWordGroupRows } from "../stage-a4/runtime-tsv";
import { buildLevel4LineProposals,combineRulesAndRescue,consolidateLineCandidates,filterToRulesUncoveredVerticalGaps,type StageA5SelectiveRow } from "../stage-a5/selective-tsv";
import { traceWordFallbackEligibility } from "../stage-a8/structure-trace";
import { buildSparseTextWordRows,detectAutoStructuralAbnormality,filterNovelRowsAgainstExisting } from "../stage-a9/targeted-split-alt";
import { decorateAltTopology,inferHorizontalColumnLanes } from "../stage-a11/anchored-lattice";
import { runPhaseLockedLattice } from "../stage-a12/phase-lattice";
import { selectLatePhaseReconsideration } from "../stage-a14/late-reconsideration";
import { applyA17LateCandidateRuntimeGate } from "../stage-a17/runtime-gate";
import type { FieldKey } from "./recognition";

export type CandidateRow={top:number;bottom:number;center:number;source:string};
export type ColumnBoxes=Record<FieldKey,{x1:number;x2:number}>;
export type CellCrop={field:FieldKey;rowIndex:number;canvas:HTMLCanvasElement;blob:Blob;preview:string;width:number;height:number;padding:number;upscale:number;contrast:number;sharpness:number;cropHasSignal:boolean};

function loadImage(file:File){return new Promise<HTMLImageElement>((resolve,reject)=>{const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("画像を開けませんでした。"))};img.src=url;});}
export async function orientedCanvas(file:File,maxSide=1800){const img=await loadImage(file);const rotate=img.naturalHeight>img.naturalWidth*1.08;const sw=rotate?img.naturalHeight:img.naturalWidth,sh=rotate?img.naturalWidth:img.naturalHeight,s=Math.min(1,maxSide/Math.max(sw,sh));const c=document.createElement("canvas");c.width=Math.max(1,Math.round(sw*s));c.height=Math.max(1,Math.round(sh*s));const ctx=c.getContext("2d",{willReadFrequently:true});if(!ctx)throw new Error("canvas unavailable");ctx.fillStyle="#fff";ctx.fillRect(0,0,c.width,c.height);if(rotate){ctx.save();ctx.translate(0,c.height);ctx.rotate(-Math.PI/2);ctx.drawImage(img,0,0,c.height,c.width);ctx.restore();}else ctx.drawImage(img,0,0,c.width,c.height);return{canvas:c,rotate};}
async function fileCanvas(file:File){const img=await loadImage(file);const c=document.createElement("canvas");c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext("2d",{willReadFrequently:true});if(!ctx)throw new Error("canvas unavailable");ctx.drawImage(img,0,0);return c;}
export function detectPaperBox(canvas:HTMLCanvasElement):CropBox{const ctx=canvas.getContext("2d",{willReadFrequently:true});if(!ctx)return{x:0,y:0,w:canvas.width,h:canvas.height};const{width:w,height:h}=canvas,p=ctx.getImageData(0,0,w,h).data,step=Math.max(2,Math.floor(Math.max(w,h)/800));const isPaper=(r:number,g:number,b:number)=>{const bright=(r+g+b)/3,yellow=r>100&&g>95&&r+g>b*1.75;return bright>150||yellow};const ys:number[]=[];for(let y=0;y<h;y+=step){let hit=0,count=0;for(let x=0;x<w;x+=step){const i=(y*w+x)*4;if(isPaper(p[i],p[i+1],p[i+2]))hit++;count++;}if(count&&hit/count>.18)ys.push(y);}if(ys.length<4)return{x:0,y:0,w,h};const top=Math.max(0,ys[0]-step*2),roughBottom=Math.min(h-1,ys[ys.length-1]+step*2),xs:number[]=[];for(let x=0;x<w;x+=step){let hit=0,count=0;for(let y=top;y<=roughBottom;y+=step){const i=(y*w+x)*4;if(isPaper(p[i],p[i+1],p[i+2]))hit++;count++;}if(count&&hit/count>.2)xs.push(x);}const left=xs.length?Math.max(0,xs[0]-step*2):0,right=xs.length?Math.min(w-1,xs[xs.length-1]+step*2):w-1,width=right-left+1;let bh=roughBottom-top+1;const expected=Math.round(width/1.74);if(width/bh<1.55&&expected<bh)bh=Math.min(expected,h-top);if(width<w*.55||bh<h*.25)return{x:0,y:0,w,h};return{x:left,y:top,w:width,h:bh};}
function canvasBlob(c:HTMLCanvasElement,q=.96){return new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error("blob failed")),"image/jpeg",q));}
function rulesRows(rgba:Uint8ClampedArray,width:number,height:number,paper:CropBox):StageA5SelectiveRow[]{const rules=detectHorizontalRuleBands(rgba,width,height,paper);return rowBandsFromRules(rules,paper).map(r=>({top:r.top,bottom:r.bottom,center:r.center,source:"rules" as const}));}
function asRows(rows:Array<{top:number;bottom:number;center:number;source:string}>):CandidateRow[]{return rows.map(r=>({...r}));}
function dedupeRows(rows:CandidateRow[],paper:CropBox){const sorted=[...rows].filter(r=>{const n=(r.center-paper.y)/paper.h;return n>.39&&n<.93}).sort((a,b)=>a.center-b.center),out:CandidateRow[]=[];for(const r of sorted){const prev=out[out.length-1];if(!prev||Math.abs(r.center-prev.center)>paper.h*.018)out.push(r);else if((r.bottom-r.top)<(prev.bottom-prev.top))out[out.length-1]=r;}return out;}

export async function getA19DynamicRows(worker:any,tesseract:any,file:File,color:any,paper:CropBox){const colorCtx=color.canvas.getContext("2d",{willReadFrequently:true});if(!colorCtx)throw new Error("geometry unavailable");const rgba=colorCtx.getImageData(0,0,color.canvas.width,color.canvas.height).data,prepared=await prepareOCRInputFile(file),ocrSource=await fileCanvas(prepared);if(ocrSource.width!==color.canvas.width||ocrSource.height!==color.canvas.height)throw new Error("OCR/geometry coordinate mismatch");const blob=await canvasBlob(ocrSource,.96);
await worker.setParameters({preserve_interword_spaces:"1",tessedit_pageseg_mode:tesseract.PSM?.AUTO??"3",user_defined_dpi:"300",tessedit_char_whitelist:""});const auto=await worker.recognize(blob,{}, {blocks:false,text:false,layoutBlocks:false,hocr:false,tsv:true,box:false,unlv:false,osd:false,pdf:false,imageColor:false,imageGrey:false,imageBinary:false,debug:false});const autoParsed=parseHeaderlessRuntimeTsv(String(auto.data.tsv||"")),wordGroups=tsvWordGroupRows(autoParsed.records,paper),ruleRows=rulesRows(rgba,color.canvas.width,color.canvas.height,paper),lineBuild=buildLevel4LineProposals(autoParsed.records,paper),consolidated=consolidateLineCandidates(lineBuild.lines),gapSelective=filterToRulesUncoveredVerticalGaps(ruleRows,consolidated.rows),dRows=combineRulesAndRescue(ruleRows,gapSelective.rows),autoWordHeights=autoParsed.records.filter((r:any)=>r.level===5&&r.height>0).map((r:any)=>r.height),maxAutoWordHeight=autoWordHeights.length?Math.max(...autoWordHeights):0,pathological=lineBuild.trace.level5WordCountInsidePaper<=1&&maxAutoWordHeight>paper.h*.5,autoFallbackTrace=traceWordFallbackEligibility({records:autoParsed.records,paper,level4LineCount:lineBuild.trace.level4LineCountInsidePaper,pathological}),autoAbnormal=detectAutoStructuralAbnormality({pathological,autoWordCount:autoFallbackTrace.wordCount,autoRowClusterCount:autoFallbackTrace.clustering.rowClusterCount,autoLevel4LineCount:lineBuild.trace.level4LineCountInsidePaper});
await worker.setParameters({preserve_interword_spaces:"1",tessedit_pageseg_mode:tesseract.PSM?.SPARSE_TEXT??"11",user_defined_dpi:"300",tessedit_char_whitelist:""});const alt=await worker.recognize(blob,{}, {blocks:false,text:false,layoutBlocks:false,hocr:false,tsv:true,box:false,unlv:false,osd:false,pdf:false,imageColor:false,imageGrey:false,imageBinary:false,debug:false});const altParsed=parseHeaderlessRuntimeTsv(String(alt.data.tsv||"")),altProposals=buildSparseTextWordRows({records:altParsed.records,paper}),altNovel=autoAbnormal.eligible?filterNovelRowsAgainstExisting({existing:dRows,proposed:altProposals.rows}):{rows:[],trace:{inputCount:altProposals.rows.length,existingCount:dRows.length,outputCount:0,altOnlyCandidateCount:0,rejectedNearExisting:0,medianReferenceHeight:0,adaptiveMargin:0}},laneInfo=inferHorizontalColumnLanes({records:altParsed.records,paper}),topology=decorateAltTopology({altRows:altNovel.rows,altRecords:altParsed.records,paper,lanes:laneInfo.lanes,laneTolerance:laneInfo.trace.laneTolerance,dRows,rawLines:lineBuild.lines,wordGroups:wordGroups.rows,ruleRows}),phaseP=runPhaseLockedLattice({dRows,altRows:topology.rows,rawLines:lineBuild.lines,wordGroups:wordGroups.rows,ruleRows,selfSeeded:false}),lateSelection=selectLatePhaseReconsideration({topologyRows:topology.rows,phaseResult:phaseP}),a17=applyA17LateCandidateRuntimeGate({topologyRows:topology.rows,phaseResult:phaseP,lateSelection}),pAlt=phaseP.acceptedCandidateIndexes.map((i:number)=>altNovel.rows[i-1]).filter(Boolean),late=a17.acceptedCandidateIndexes.map((i:number)=>altNovel.rows[i-1]).filter(Boolean);return{rows:dedupeRows([...asRows(dRows),...pAlt.map((r:any)=>({top:r.top,bottom:r.bottom,center:r.center,source:"a12-phase"})),...late.map((r:any)=>({top:r.top,bottom:r.bottom,center:r.center,source:"a17-late"}))],paper),phaseP,a17,ocrCanvas:ocrSource};}

const FIXED_COLUMNS:ColumnBoxes={name:{x1:.025,x2:.395},qty:{x1:.432,x2:.472},retail:{x1:.480,x2:.570},cost:{x1:.596,x2:.676}};
export function adaptiveColumns(canvas:HTMLCanvasElement,paper:CropBox):{boxes:ColumnBoxes;rules:number[]}{const ctx=canvas.getContext("2d",{willReadFrequently:true});if(!ctx)return{boxes:FIXED_COLUMNS,rules:[]};const img=ctx.getImageData(0,0,canvas.width,canvas.height).data,y1=Math.max(paper.y,Math.round(paper.y+paper.h*.35)),y2=Math.min(canvas.height-1,Math.round(paper.y+paper.h*.92)),stepY=Math.max(1,Math.round(paper.h/350)),scores:Array<{x:number;s:number}>=[];for(let x=paper.x;x<paper.x+paper.w;x+=2){let dark=0,n=0;for(let y=y1;y<=y2;y+=stepY){const i=(y*canvas.width+x)*4,v=(img[i]+img[i+1]+img[i+2])/3;if(v<120)dark++;n++;}scores.push({x,s:n?dark/n:0});}const peaks=scores.filter(v=>v.s>.18).sort((a,b)=>b.s-a.s),picked:number[]=[];for(const p of peaks){const xn=(p.x-paper.x)/paper.w;if(xn<.015||xn>.90)continue;if(picked.every(q=>Math.abs(q-xn)>.012))picked.push(xn);if(picked.length>=14)break;}const nearest=(expected:number,radius=.055)=>{const c=picked.filter(v=>Math.abs(v-expected)<=radius).sort((a,b)=>Math.abs(a-expected)-Math.abs(b-expected));return c[0]??expected},b0=nearest(.02,.04),b1=nearest(.405),b2=nearest(.425,.04),b3=nearest(.475,.04),b4=nearest(.575,.05),b5=nearest(.590,.04),b6=nearest(.685,.06),safe=(a:number,b:number,fa:number,fb:number)=>b-a>.018?{x1:a+.004,x2:b-.004}:{x1:fa,x2:fb};return{boxes:{name:safe(b0,b1,.025,.395),qty:safe(b2,b3,.432,.472),retail:safe(b3,b4,.480,.570),cost:safe(b5,b6,.596,.676)},rules:picked.sort((a,b)=>a-b)};}

function sharpnessOf(data:Uint8ClampedArray,w:number,h:number){let sum=0,n=0;for(let y=1;y<h-1;y+=2)for(let x=1;x<w-1;x+=2){const p=(y*w+x)*4,c=data[p],l=data[p-4],r=data[p+4],u=data[p-w*4],d=data[p+w*4],lap=4*c-l-r-u-d;sum+=lap*lap;n++;}return n?Math.sqrt(sum/n):0;}
export async function makeCellCrop(canvas:HTMLCanvasElement,paper:CropBox,row:CandidateRow,col:{x1:number;x2:number},field:FieldKey,rowIndex:number,target=1100):Promise<CellCrop>{const yPad=Math.max(1,(row.bottom-row.top)*.10),x=paper.x+paper.w*col.x1,w=paper.w*(col.x2-col.x1),y=row.top+yPad,h=Math.max(2,row.bottom-row.top-yPad*2),scale=Math.min(6,Math.max(1,target/w)),out=document.createElement("canvas");out.width=Math.max(1,Math.round(w*scale));out.height=Math.max(1,Math.round(h*scale));const ctx=out.getContext("2d",{willReadFrequently:true});if(!ctx)throw new Error("crop unavailable");ctx.fillStyle="#fff";ctx.fillRect(0,0,out.width,out.height);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.drawImage(canvas,x,y,w,h,0,0,out.width,out.height);const image=ctx.getImageData(0,0,out.width,out.height);let min=255,max=0,dark=0;for(let i=0;i<image.data.length;i+=4){const r=image.data[i],g=image.data[i+1],b=image.data[i+2];let v=Math.round(r*.20+g*.72+b*.08);v=Math.max(0,Math.min(255,Math.round((v-128)*1.28+148)));if(v>246)v=255;min=Math.min(min,v);max=Math.max(max,v);if(v<190)dark++;image.data[i]=image.data[i+1]=image.data[i+2]=v;}ctx.putImageData(image,0,0);const contrast=max-min,sharpness=sharpnessOf(image.data,out.width,out.height),signalRatio=dark/Math.max(1,out.width*out.height),cropHasSignal=contrast>=35&&signalRatio>.002,blob=await canvasBlob(out,.96),preview=out.toDataURL("image/jpeg",.7);return{field,rowIndex,canvas:out,blob,preview,width:out.width,height:out.height,padding:yPad,upscale:scale,contrast,sharpness,cropHasSignal};}
