"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { EXPECTED_FILES } from "../stage-a4/gt";

type GtRow = { name: string; qty: string; retail: string; cost: string };
type GtMap = Record<string, GtRow[]>;
type PreviewMap = Record<string, { url: string; originalName: string }>;
const STORAGE_KEY = "icb.parts-ocr.stage-a19.four-field-gt.v1";
const EMPTY_ROW: GtRow = { name: "", qty: "", retail: "", cost: "" };
function blankMap(): GtMap { return Object.fromEntries(EXPECTED_FILES.map((f) => [f, [{ ...EMPTY_ROW }]])); }
function normalizeStored(value: unknown): GtMap { const base=blankMap(); if(!value||typeof value!=="object")return base; for(const f of EXPECTED_FILES){const rows=(value as Record<string,unknown>)[f];if(!Array.isArray(rows)||!rows.length)continue;base[f]=rows.map((r)=>{const v=r&&typeof r==="object"?r as Record<string,unknown>:{};return{name:String(v.name??""),qty:String(v.qty??""),retail:String(v.retail??""),cost:String(v.cost??"")};});}return base; }
function canonical(name:string){const m=name.match(/IMG_(067[5-9]|068[0-6])/i);return m?EXPECTED_FILES.find((f)=>f.startsWith(`IMG_${m[1]}`))||"":"";}
function evalInput(){return document.querySelector('main input[type="file"][multiple]') as HTMLInputElement|null;}
export default function GtBuilderEnhancer(){
 const[gt,setGt]=useState<GtMap>(()=>blankMap());const[loaded,setLoaded]=useState(false);const[saveState,setSaveState]=useState("未保存");const[previews,setPreviews]=useState<PreviewMap>({});const[state,setState]=useState("最初に黄色正式12枚を一括選択してください。");const urls=useRef<string[]>([]);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)setGt(normalizeStored(JSON.parse(raw)));}catch{setSaveState("保存済みGT読込失敗");}finally{setLoaded(true);}},[]);
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(gt));setSaveState("ブラウザに自動保存済み");}catch{setSaveState("ブラウザ保存失敗");}},[gt,loaded]);
 useEffect(()=>{const capture=(event:Event)=>{const target=event.target;if(!(target instanceof HTMLInputElement)||target.type!=="file"||!target.multiple||!target.closest("main"))return;if(target.dataset.a20AllowRun==="1")return;event.preventDefault();event.stopPropagation();const files=Array.from(target.files||[]);urls.current.forEach(URL.revokeObjectURL);urls.current=[];const next:PreviewMap={},dup:string[]=[],unknown:string[]=[];for(const file of files){const id=canonical(file.name);if(!id){unknown.push(file.name);continue;}if(next[id]){dup.push(file.name);continue;}const url=URL.createObjectURL(file);urls.current.push(url);next[id]={url,originalName:file.name};}setPreviews(next);const missing=EXPECTED_FILES.filter((id)=>!next[id]);setState([`対応確認 ${Object.keys(next).length}/12`,missing.length?`不足: ${missing.join(", ")}`:"12枚すべて1対1対応済み",dup.length?`重複: ${dup.join(", ")}`:"",unknown.length?`対象外: ${unknown.join(", ")}`:""].filter(Boolean).join(" / "));};document.addEventListener("change",capture,true);return()=>{document.removeEventListener("change",capture,true);urls.current.forEach(URL.revokeObjectURL);};},[]);
 useEffect(()=>{const hide=()=>{const input=evalInput();if(!input)return false;input.closest("section")?.querySelectorAll("button").forEach((b)=>{if(b.textContent?.includes("黄色正式12枚"))(b as HTMLButtonElement).style.display="none";});return true;};if(!hide()){const t=window.setInterval(()=>{if(hide())window.clearInterval(t);},100);return()=>window.clearInterval(t);}},[]);
 const completed=useMemo(()=>EXPECTED_FILES.filter((f)=>(gt[f]||[]).some((r)=>r.name.trim()||r.qty.trim()||r.retail.trim()||r.cost.trim())).length,[gt]);const selected=EXPECTED_FILES.filter((f)=>previews[f]).length;
 const update=(f:string,i:number,k:keyof GtRow,v:string)=>setGt((cur)=>({...cur,[f]:cur[f].map((r,n)=>n===i?{...r,[k]:v}:r)}));const add=(f:string)=>setGt((cur)=>({...cur,[f]:[...cur[f],{...EMPTY_ROW}]}));const remove=(f:string,i:number)=>setGt((cur)=>{const rows=cur[f].filter((_,n)=>n!==i);return{...cur,[f]:rows.length?rows:[{...EMPTY_ROW}]};});
 const choose=()=>{const input=evalInput();if(input)input.click();else setState("評価用画像選択欄が見つかりません。再読み込みしてください。");};
 const run=()=>{const input=evalInput();if(!input?.files?.length){setState("先に正式12枚を選択してください。");return;}const missing=EXPECTED_FILES.filter((f)=>!previews[f]);if(missing.length){setState(`写真対応が未完了: ${missing.join(", ")}`);return;}if(completed!==12){setState(`GT未入力があります。${completed}/12`);return;}input.dataset.a20AllowRun="1";input.dispatchEvent(new Event("change",{bubbles:true}));window.setTimeout(()=>delete input.dataset.a20AllowRun,0);};
 return <section style={{maxWidth:1120,margin:"16px auto 0",padding:"0 12px"}}><div style={{background:"#fff",border:"1px solid #dbe2ec",borderRadius:16,padding:14}}><h2 style={{marginTop:0}}>Stage A20 正式12枚・4項目GT</h2><p>同じ12枚をここで一度だけ選択します。IMG_0675〜IMG_0686へ自動対応し、サムネイル横の表へ実伝票の印字を入力してください。GTはscoring-onlyです。</p><button type="button" onClick={choose} style={{width:"100%",border:0,borderRadius:12,padding:12,background:"#174ea6",color:"#fff",fontWeight:800,fontSize:16}}>黄色正式12枚を一括選択して写真対応を確認</button><div style={{margin:"10px 0 12px",fontSize:13}}>写真対応 {selected}/12 ・ GT入力 {completed}/12 ・ {saveState}<br/>{state}</div>{EXPECTED_FILES.map((f)=>{const p=previews[f];return <details key={f} open={f===EXPECTED_FILES[0]} style={{borderTop:"1px solid #e5e9f0",padding:"10px 0"}}><summary style={{fontWeight:800}}>{f}</summary><div style={{display:"grid",gridTemplateColumns:"minmax(120px,220px) 1fr",gap:12,marginTop:10}}><div>{p?<><img src={p.url} alt={`${f}対応画像`} style={{width:"100%",maxHeight:220,objectFit:"contain",border:"1px solid #ccd5e3",borderRadius:10}}/><div style={{fontSize:12,overflowWrap:"anywhere"}}>対応: <strong>{p.originalName}</strong></div></>:<div style={{minHeight:120,border:"1px dashed #c6ceda",borderRadius:10,display:"grid",placeItems:"center",textAlign:"center"}}>{f}<br/>対応画像未選択</div>}</div><div style={{overflowX:"auto"}}><table style={{width:"100%",minWidth:700}}><thead><tr><th>#</th><th>部品名称</th><th>個数</th><th>定価</th><th>仕入れ</th><th/></tr></thead><tbody>{(gt[f]||[]).map((r,i)=><tr key={`${f}-${i}`}><td>{i+1}</td>{(["name","qty","retail","cost"] as const).map((k)=><td key={k}><input value={r[k]} onChange={(e)=>update(f,i,k,e.target.value)} inputMode={k==="name"?"text":"numeric"} style={{width:"100%",padding:8,boxSizing:"border-box"}}/></td>)}<td><button type="button" onClick={()=>remove(f,i)}>削除</button></td></tr>)}</tbody></table><button type="button" onClick={()=>add(f)}>＋ 行追加</button></div></div></details>})}<button type="button" onClick={run} disabled={selected!==12||completed!==12} style={{width:"100%",border:0,borderRadius:13,padding:14,marginTop:14,background:selected===12&&completed===12?"#2468df":"#aeb8c7",color:"#fff",fontWeight:800,fontSize:17}}>この12枚とGTで3 recognition方式を1run</button></div></section>;
}
