/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useEffect,useMemo,useRef,useState } from "react";
import { EXPECTED_FILES } from "../stage-a4/gt";
import { adaptiveColumns,detectPaperBox,getA19DynamicRows,makeCellCrop,orientedCanvas,type CellCrop } from "./a19-table-crops";
import { getModelStats,recognizeOnnx,recognizeTess,type FieldKey,type RecognitionResult } from "./recognition";
import { canonicalImageId,downloadPredictionExport,relationFor,type StagePredictionExport } from "../corrected-rescore/prediction-export";

type FieldRow={name:string;qty:string;retail:string;cost:string};
type EngineKey="CONTROL_TESS"|"ONNX_JA_LIGHT"|"ONNX_V5";
const ENGINES:EngineKey[]=["CONTROL_TESS","ONNX_JA_LIGHT","ONNX_V5"];
const FIELDS:FieldKey[]=["name","qty","retail","cost"];
const GT_STORAGE="icb.parts-ocr.stage-a19.four-field-gt.v1";
const RUN_MARKER="icb.parts-ocr.stage-a20.running";
const REVISION="stage-a20-recognition-engine-isolation-v1";
const FROZEN_HEAD="6a31ec4b9028410e90a8dbd9c8b40d53de7742d2";
const A19_SOURCE="2fc3655306842417724e5c16f0bbe2766b691b2b";
const EVAL_HEAD=process.env.NEXT_PUBLIC_EVAL_HEAD||"unknown-preview-head";
const styles:Record<string,React.CSSProperties>={page:{maxWidth:1120,margin:"0 auto",padding:"16px 12px 60px",background:"#f5f7fb",minHeight:"100vh",color:"#172033"},card:{background:"#fff",border:"1px solid #dbe2ec",borderRadius:16,padding:14,marginBottom:12},primary:{width:"100%",border:0,borderRadius:13,padding:"14px 12px",background:"#2468df",color:"#fff",fontWeight:800,fontSize:17},pre:{whiteSpace:"pre-wrap",overflowWrap:"anywhere",background:"#f7f9fc",border:"1px solid #e2e7ef",borderRadius:10,padding:10,fontSize:11,lineHeight:1.45,maxHeight:700,overflow:"auto"}};
function canonicalFromName(name:string){const m=name.match(/IMG_(067[5-9]|068[0-6])/i);return m?`IMG_${m[1]}(1)`:"";}
function norm(v:string){return v.normalize("NFKC").replace(/[￥¥,\s]/g,"").toUpperCase();}
function score(gt:FieldRow[],pred:FieldRow[]){const byField:any={name:{correct:0,total:gt.length},qty:{correct:0,total:gt.length},retail:{correct:0,total:gt.length},cost:{correct:0,total:gt.length}};let correct=0,blank=0,misread=0,complete=0;for(let i=0;i<gt.length;i++){const p=pred[i]||{name:"",qty:"",retail:"",cost:""};let ok=true;for(const k of FIELDS){const a=norm(gt[i][k]),b=norm(p[k]);if(a&&a===b){correct++;byField[k].correct++;}else{ok=false;if(!b)blank++;else misread++;}}if(ok)complete++;}const total=gt.length*4;return{rows:gt.length,predRows:pred.length,correct,total,accuracy:total?correct/total:0,complete,completeRate:gt.length?complete/gt.length:0,blank,misread,falseRows:Math.max(0,pred.length-gt.length),missingRows:Math.max(0,gt.length-pred.length),byField};}
function memoryNow(){const m=(performance as any).memory;return m&&typeof m.usedJSHeapSize==="number"?{available:true,usedJSHeapSize:m.usedJSHeapSize,totalJSHeapSize:m.totalJSHeapSize,jsHeapSizeLimit:m.jsHeapSizeLimit}:{available:false,note:"Safari/iOS does not expose performance.memory; model bytes and crash/reload marker are recorded instead."};}
function loadGt():Record<string,FieldRow[]>{try{const raw=localStorage.getItem(GT_STORAGE);const v=raw?JSON.parse(raw):{};return v&&typeof v==="object"?v:{}}catch{return{};}}
function pct(v:number){return(v*100).toFixed(2)+"%";}

export default function StageA20Page(){
 const inputRef=useRef<HTMLInputElement>(null);const[busy,setBusy]=useState(false);const[status,setStatus]=useState("A19で保存したGTを確認してから、黄色正式12枚を一括選択してください。");const[result,setResult]=useState<any>(null);const[cropAudit,setCropAudit]=useState<any[]>([]);const[copyState,setCopyState]=useState("");const[priorReload,setPriorReload]=useState(false);const[gtCount,setGtCount]=useState(0);
 useEffect(()=>{const marker=sessionStorage.getItem(RUN_MARKER);if(marker)setPriorReload(true);const gt=loadGt();setGtCount(EXPECTED_FILES.filter((f:string)=>Array.isArray(gt[f])&&gt[f].some((r:FieldRow)=>FIELDS.some((k:FieldKey)=>String(r?.[k]||"").trim()))).length);},[]);
 async function run(files:FileList|null){if(!files?.length)return;const gtMap=loadGt(),missingGt=EXPECTED_FILES.filter((id:string)=>!gtMap[id]?.length);if(missingGt.length){setStatus(`A19 GT不足: ${missingGt.join(", ")}`);return;}const byCanonical=new Map<string,File>();for(const f of Array.from(files)){const id=canonicalFromName(f.name);if(id&&!byCanonical.has(id))byCanonical.set(id,f);}const missing=EXPECTED_FILES.filter((id:string)=>!byCanonical.has(id));if(missing.length){setStatus(`画像missing: ${missing.join(", ")}`);return;}
 setBusy(true);setResult(null);setCropAudit([]);sessionStorage.setItem(RUN_MARKER,new Date().toISOString());let worker:any=null;const memoryBefore=memoryNow();try{const tesseract:any=await import("tesseract.js");worker=await tesseract.createWorker("jpn+eng",1);setStatus("ONNXモデルを初回load中…");const [lightStats,v5Stats]=await Promise.all([getModelStats("ONNX_JA_LIGHT"),getModelStats("ONNX_V5")]);const modelStats:any={ONNX_JA_LIGHT:lightStats,ONNX_V5:v5Stats};const images:any[]=[],allCrops:any[]=[];
 for(let i=0;i<EXPECTED_FILES.length;i++){const fileName=EXPECTED_FILES[i],file=byCanonical.get(fileName)!,gt=gtMap[fileName] as FieldRow[],imageStart=performance.now();setStatus(`${i+1}/12 ${fileName} A19_TABLE geometry…`);const color=await orientedCanvas(file),paper=detectPaperBox(color.canvas),dynamic=await getA19DynamicRows(worker,tesseract,file,color,paper),adaptive=adaptiveColumns(color.canvas,paper);const rows=dynamic.rows;const cellCrops:CellCrop[][]=[];for(let r=0;r<rows.length;r++){const row:CellCrop[]=[];for(const field of FIELDS){row.push(await makeCellCrop(dynamic.ocrCanvas,paper,rows[r],adaptive.boxes[field],field,r,field==="name"?1600:900));}cellCrops.push(row);}const engineRows:any={CONTROL_TESS:[],ONNX_JA_LIGHT:[],ONNX_V5:[]};const engineMs:any={CONTROL_TESS:0,ONNX_JA_LIGHT:0,ONNX_V5:0};const cells:any[]=[];
 for(let r=0;r<cellCrops.length;r++){const outRows:any={CONTROL_TESS:{name:"",qty:"",retail:"",cost:""},ONNX_JA_LIGHT:{name:"",qty:"",retail:"",cost:""},ONNX_V5:{name:"",qty:"",retail:"",cost:""}};for(const cell of cellCrops[r]){setStatus(`${i+1}/12 ${fileName} row ${r+1} ${cell.field} recognition…`);const recs:Partial<Record<EngineKey,RecognitionResult&{error?:string}>>={};const tess=await recognizeTess(worker,tesseract,cell.blob,cell.field);recs.CONTROL_TESS=tess;engineMs.CONTROL_TESS+=tess.latencyMs;outRows.CONTROL_TESS[cell.field]=tess.normalized;
 for(const engine of ["ONNX_JA_LIGHT","ONNX_V5"] as const){if(!modelStats[engine]?.available){recs[engine]={raw:"",confidence:null,normalized:"",latencyMs:0,error:modelStats[engine]?.error||"model unavailable"};continue;}try{const rr=await recognizeOnnx(engine,cell.canvas,cell.field);recs[engine]=rr;engineMs[engine]+=rr.latencyMs;outRows[engine][cell.field]=rr.normalized;}catch(e:any){recs[engine]={raw:"",confidence:null,normalized:"",latencyMs:0,error:String(e?.message||e)};}}
 cells.push({rowIndex:r,field:cell.field,crop:{preview:cell.preview,width:cell.width,height:cell.height,padding:cell.padding,upscale:cell.upscale,contrast:cell.contrast,sharpness:cell.sharpness,crop_has_signal:cell.cropHasSignal},recognition:recs});}
 for(const e of ENGINES){const row=outRows[e];if(row.name||row.qty||row.retail||row.cost)engineRows[e].push(row);} }
 const methods:any={};for(const e of ENGINES)methods[e]={rows:engineRows[e],score:score(gt,engineRows[e]),recognitionMs:Math.round(engineMs[e])};const cropSummary={total:cells.length,withSignal:cells.filter((c:any)=>c.crop.crop_has_signal).length,withoutSignal:cells.filter((c:any)=>!c.crop.crop_has_signal).length,blankDespiteSignal:Object.fromEntries(ENGINES.map((e:EngineKey)=>[e,cells.filter((c:any)=>c.crop.crop_has_signal&&!c.recognition[e]?.normalized).length]))};images.push({fileName,gtRows:gt.length,dynamicRowCount:rows.length,verticalRuleNorm:adaptive.rules,methods,cropSummary,totalMs:Math.round(performance.now()-imageStart)});allCrops.push({fileName,cells});}
 const aggregate=(e:EngineKey)=>{const xs=images.map((x:any)=>x.methods[e]),total=xs.reduce((s:number,x:any)=>s+x.score.total,0),correct=xs.reduce((s:number,x:any)=>s+x.score.correct,0),gtRows=xs.reduce((s:number,x:any)=>s+x.score.rows,0);const byField:any={};for(const f of FIELDS){const c=xs.reduce((s:number,x:any)=>s+x.score.byField[f].correct,0),t=xs.reduce((s:number,x:any)=>s+x.score.byField[f].total,0);byField[f]={correct:c,total:t,accuracy:t?c/t:0};}const cellLatencies=allCrops.flatMap((x:any)=>x.cells.map((c:any)=>c.recognition[e]?.latencyMs||0)).filter((x:number)=>x>0);return{fieldCorrect:correct,fieldTotal:total,fieldAccuracy:total?correct/total:0,completeRows:xs.reduce((s:number,x:any)=>s+x.score.complete,0),gtRows,completeRowRate:gtRows?xs.reduce((s:number,x:any)=>s+x.score.complete,0)/gtRows:0,falseRows:xs.reduce((s:number,x:any)=>s+x.score.falseRows,0),missingRows:xs.reduce((s:number,x:any)=>s+x.score.missingRows,0),misreadFields:xs.reduce((s:number,x:any)=>s+x.score.misread,0),blankFields:xs.reduce((s:number,x:any)=>s+x.score.blank,0),processingMs:xs.reduce((s:number,x:any)=>s+x.recognitionMs,0),meanCellLatencyMs:cellLatencies.length?Math.round(cellLatencies.reduce((a:number,b:number)=>a+b,0)/cellLatencies.length):0,meanRowLatencyMs:cellLatencies.length?Math.round(cellLatencies.reduce((a:number,b:number)=>a+b,0)/(cellLatencies.length/4)):0,meanSlipRecognitionMs:Math.round(xs.reduce((s:number,x:any)=>s+x.recognitionMs,0)/12),byField};};
 const summary={schema:"icb.parts-ocr.stage-a20-recognition-engine-isolation.v1",revision:REVISION,evalHead:EVAL_HEAD,frozenHead:FROZEN_HEAD,a19Source:A19_SOURCE,gtRuntimeUse:false,gtScoringOnly:true,sharedA19TableCrops:true,positioningDifference:false,guidedLive:false,paidApi:false,models:modelStats,memory:{before:memoryBefore,after:memoryNow()},priorReloadDetected:priorReload,methods:Object.fromEntries(ENGINES.map((e:EngineKey)=>[e,aggregate(e)])),cropAudit:{totalCells:allCrops.reduce((s:number,x:any)=>s+x.cells.length,0),withSignal:allCrops.reduce((s:number,x:any)=>s+x.cells.filter((c:any)=>c.crop.crop_has_signal).length,0),withoutSignal:allCrops.reduce((s:number,x:any)=>s+x.cells.filter((c:any)=>!c.crop.crop_has_signal).length,0),blankDespiteSignal:Object.fromEntries(ENGINES.map((e:EngineKey)=>[e,allCrops.reduce((s:number,x:any)=>s+x.cells.filter((c:any)=>c.crop.crop_has_signal&&!c.recognition[e]?.normalized).length,0)]))},images};setCropAudit(allCrops);setResult(summary);setStatus("Stage A20正式12枚比較完了。総合管理用summaryをコピーしてください。");sessionStorage.removeItem(RUN_MARKER);
 }catch(e:any){console.error(e);setStatus(`ERROR: ${e?.message||e}`);}finally{if(worker)await worker.terminate().catch(()=>{});setBusy(false);}}
 const short=useMemo(()=>result?JSON.stringify({...result,images:result.images.map((x:any)=>({fileName:x.fileName,gtRows:x.gtRows,dynamicRowCount:x.dynamicRowCount,methods:Object.fromEntries(ENGINES.map((e:EngineKey)=>[e,x.methods[e].score])),cropSummary:x.cropSummary,totalMs:x.totalMs}))},null,2):"",[result]);async function copy(){if(!short)return;await navigator.clipboard.writeText(short);setCopyState("コピー済み");}
 function exportPredictions(){if(!result)return;const payload:StagePredictionExport={schema:"icb.parts-ocr.prediction-export.v2",stage:"A20",timestamp:new Date().toISOString(),runtimeConfigIdentifier:`${REVISION}@${EVAL_HEAD}`,gtIncluded:false,images:result.images.map((image:any)=>{const imageId=canonicalImageId(image.fileName),relation=relationFor(imageId);return{imageId,...relation,engines:Object.fromEntries(ENGINES.map((engine)=>[engine,{rows:(image.methods[engine].rows||[]).map((fields:FieldRow,rowIndex:number)=>({rowIndex,fields,confidence:{name:null,qty:null,retail:null,cost:null}})),processingTimeMs:image.methods[engine].recognitionMs??null,error:null}]))};})};downloadPredictionExport(payload);setCopyState("GTなしprediction JSONを保存しました");}
 return <main style={styles.page}><section style={styles.card}><h1 style={{margin:0}}>Stage A20 Recognition Engine Isolation PoC</h1><p>同一A19_TABLE row / column / cell cropで、recognition engineだけを比較。GTはscoring-only。</p><small>Frozen {FROZEN_HEAD.slice(0,12)} / A19 {A19_SOURCE.slice(0,12)} / Preview {EVAL_HEAD.slice(0,12)}</small></section><section style={styles.card}><h2>正式12枚</h2><p>A19で保存したGTは既存historical表示の採点だけに使われ、prediction exportには含めません。</p><input ref={inputRef} hidden type="file" accept="image/*" multiple onChange={e=>run(e.target.files)}/><button disabled={busy||gtCount!==12} style={{...styles.primary,background:busy||gtCount!==12?"#aeb8c7":"#2468df"}} onClick={()=>inputRef.current?.click()}>{busy?"評価中…":"黄色正式12枚を選択して3 recognition方式を1run"}</button><div style={{marginTop:10,fontSize:13}}>{status}</div></section>{result&&<><section style={styles.card}><button style={styles.primary} onClick={exportPredictions}>GTなしprediction JSONを保存</button><button style={{...styles.primary,marginTop:8,background:"#475569"}} onClick={copy}>historical summaryをコピー</button><div>{copyState}</div><pre style={styles.pre}>{short}</pre></section><section style={styles.card}><h2>Cell crop監査</h2>{cropAudit.map((img:any)=><details key={img.fileName}><summary>{img.fileName} ({img.cells.length} cells)</summary></details>)}</section></>}</main>;
}
