"use client";

import { useLayoutEffect } from "react";

const AUTH_EVENT = "vehicle-certificate-authoritative";
const PDF_PRIORITY_KEY = "__vehicleCertificatePdfPriority";

function norm(v) { return String(v ?? "").normalize("NFKC").replace(/[‐‑‒–—―]/g, "-").replace(/\r/g, "").replace(/[ \t]+/g, " ").trim(); }
function compact(v) { return norm(v).replace(/[\s:：・,，.。()（）\[\]［］]/g, ""); }
function token(item,w,h){const text=norm(item?.str);if(!text)return null;const tr=item?.transform||[1,0,0,1,0,0];return{text,x:Number(tr[4]||0)/Math.max(1,w),y:1-Number(tr[5]||0)/Math.max(1,h),w:Math.max(Number(item?.width||0),1)/Math.max(1,w),h:Math.max(Math.abs(Number(tr[3]||0)),Number(item?.height||0),1)/Math.max(1,h)};}
function linesFrom(tokens){const lines=[];for(const t of [...tokens].sort((a,b)=>a.y-b.y||a.x-b.x)){let l=lines.find(x=>Math.abs(x.y-t.y)<=Math.max(.0045,t.h*.72));if(!l){l={y:t.y,tokens:[]};lines.push(l);}l.tokens.push(t);l.y=l.tokens.reduce((s,x)=>s+x.y,0)/l.tokens.length;}for(const l of lines){l.tokens.sort((a,b)=>a.x-b.x);l.text=l.tokens.map(x=>x.text).join(" ");}return lines.sort((a,b)=>a.y-b.y);}
function labelAnchor(lines,label){const wanted=compact(label);for(const line of lines)for(let s=0;s<line.tokens.length;s++){let joined="";for(let e=s;e<line.tokens.length&&e<s+14;e++){joined+=compact(line.tokens[e].text);if(joined.includes(wanted))return{x:line.tokens[s].x,y:line.y,line,start:s,end:e};if(joined.length>wanted.length+22)break;}}return null;}
function cellText(tokens,a,left,right,bottom){if(!a)return"";const same=a.line.tokens.slice(a.end+1).filter(t=>t.x>=left&&t.x<right).map(t=>t.text);const below=tokens.filter(t=>t.y>a.y+.002&&t.y<bottom&&t.x>=left&&t.x<right).sort((p,q)=>p.y-q.y||p.x-q.x).map(t=>t.text);return norm([...same,...below].join(" "));}
function nextY(lines,a,labels,fallback){const ys=labels.map(l=>labelAnchor(lines,l)).filter(Boolean).filter(x=>x.y>a.y+.004).map(x=>x.y);return ys.length?Math.min(...ys)-.002:Math.min(1,a.y+fallback);}
function parseWeight(raw){const s=norm(raw).replace(/kg/ig," "),m=s.match(/(\d{2,5})(?:\s*[\[［]\s*(\d{2,5})\s*[\]］])?/);if(!m)return null;return{raw:m[2]?`${Number(m[1])} [${Number(m[2])}]`:String(Number(m[1])),primary:Number(m[1]),alternate:m[2]?Number(m[2]):null};}
function recoverWeights(tokens,lines){const defs=[["最大積載量","maxPayloadKg","maxPayload"],["車両重量","vehicleWeightKg","vehicleWeight"],["車両総重量","grossVehicleWeightKg","grossVehicleWeight"]],anchors=defs.map(([l])=>labelAnchor(lines,l));if(anchors.some(x=>!x))return{};const ordered=anchors.map((a,i)=>({a,i})).sort((p,q)=>p.a.x-q.a.x),bounds=new Map();ordered.forEach((cur,p)=>{const prev=ordered[p-1]?.a,next=ordered[p+1]?.a;bounds.set(cur.i,[prev?(prev.x+cur.a.x)/2:Math.max(0,cur.a.x-.04),next?(cur.a.x+next.x)/2:1]);});const headerBottom=Math.max(...anchors.map(a=>a.y)),stops=["車台番号","前前軸重","長さ"].map(x=>labelAnchor(lines,x)).filter(Boolean).filter(a=>a.y>headerBottom+.004),bottom=stops.length?Math.min(...stops.map(a=>a.y))-.002:headerBottom+.09,out={},evidence={};defs.forEach(([label,key,base],i)=>{const [left,right]=bounds.get(i),source=cellText(tokens,anchors[i],left,right,bottom),v=parseWeight(source);evidence[base]={label,sourceTokens:source,parsed:v};if(v){out[key]=v.raw;out[`${base}Raw`]=v.raw;out[`${base}PrimaryKg`]=v.primary;out[`${base}AlternateKg`]=v.alternate;}});out.__weightEvidence=evidence;return out;}
const ID_DEFS=[["所有者の氏名又は名称","ownerNameRaw"],["所有者の住所","ownerAddressRaw"],["使用者の氏名又は名称","userNameRaw"],["使用者の住所","userAddressRaw"]];
function cleanIdentity(v){return norm(v).replace(/\[\d+\]$/g,"").trim();}
function recoverIdentity(tokens,lines){const anchors=ID_DEFS.map(([l])=>labelAnchor(lines,l)),out={},evidence={};ID_DEFS.forEach(([label,key],i)=>{const a=anchors[i];if(!a)return;const same=anchors.filter(Boolean).filter(x=>Math.abs(x.y-a.y)<.025).sort((p,q)=>p.x-q.x),pos=same.indexOf(a),prev=same[pos-1],next=same[pos+1],left=prev?(prev.x+a.x)/2:Math.max(0,a.x-.025),right=next?(a.x+next.x)/2:1,lower=anchors.filter(Boolean).filter(x=>x.y>a.y+.008&&x.x>=left-.03&&x.x<right+.03).sort((p,q)=>p.y-q.y)[0],bottom=lower?lower.y-.002:Math.min(1,a.y+.075);let raw=cellText(tokens,a,left,right,bottom),value=cleanIdentity(raw);for(const [other] of ID_DEFS)value=value.replace(new RegExp(compact(other),"g"),"");value=cleanIdentity(value);evidence[key]={semantic:"main-table",label,sourceTokens:raw,masked:/^[*＊]+$/.test(compact(value))};if(value&&value.length<=180)out[key]=value;});out.__identityEvidence=evidence;return out;}
function recoverOwnerAtIssuance(tokens,lines){const markers=["本自動車検査証発行時における所有者情報","自動車検査証発行時における所有者情報"];let a=null,marker="";for(const m of markers){a=labelAnchor(lines,m);if(a){marker=m;break;}}if(!a)return{};const bottom=nextY(lines,a,["その他検査事項","二次元コード"],.17),region=tokens.filter(t=>t.y>a.y+.001&&t.y<bottom),rlines=linesFrom(region),out={};let name="",address="";for(const label of ["所有者の氏名又は名称","氏名又は名称"]){const x=labelAnchor(rlines,label);if(x){name=cleanIdentity(cellText(region,x,x.x,1,nextY(rlines,x,["所有者の住所","住所"],.05)));if(name)break;}}for(const label of ["所有者の住所","住所"]){const x=labelAnchor(rlines,label);if(x){address=cleanIdentity(cellText(region,x,x.x,1,nextY(rlines,x,["その他検査事項"],.06)));if(address)break;}}if(!name){const c=rlines.map(l=>norm(l.text)).filter(s=>s&&!markers.some(m=>compact(s).includes(compact(m))));name=c.find(s=>/(株式会社|有限会社|合同会社|法人|組合)/.test(s))||"";if(name&&!address){const i=c.indexOf(name);address=c.slice(i+1,i+3).find(s=>s&&!/(氏名|名称)/.test(s))||"";}}if(name)out.ownerAtIssuanceNameRaw=name;if(address)out.ownerAtIssuanceAddressRaw=address;out.__ownerAtIssuanceEvidence={semantic:"owner-at-certificate-issuance",marker,sourceTokens:region.map(t=>t.text).join(" "),name,address};return out;}
function recoverDisplacement(tokens,lines){const a=labelAnchor(lines,"総排気量又は定格出力");if(!a)return{};const bottom=nextY(lines,a,["燃料の種類","型式指定番号","類別区分番号"],.075),source=cellText(tokens,a,Math.max(0,a.x-.01),1,bottom),m=source.match(/(\d+(?:\.\d+)?)\s*(L|ℓ|l|kW|KW|kw)\b/i);if(!m)return{__displacementEvidence:{label:"総排気量又は定格出力",sourceTokens:source,parsed:null}};const unit=/^(l|ℓ)$/i.test(m[2])?"L":"kW",value=m[1];return{displacementOrRatedOutput:`${value} ${unit}`,displacementOrRatedOutputRaw:norm(m[0]),displacementOrRatedOutputValue:value,displacementOrRatedOutputUnit:unit,__displacementEvidence:{label:"総排気量又は定格出力",sourceTokens:source,parsed:{value,unit}}};}
async function extract(file){const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/legacy/build/pdf.worker.min.mjs",import.meta.url).toString();const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;try{let best=null;for(let n=1;n<=Math.min(pdf.numPages||1,8);n++){const page=await pdf.getPage(n),vp=page.getViewport({scale:1}),content=await page.getTextContent(),tokens=(content.items||[]).map(x=>token(x,vp.width,vp.height)).filter(Boolean),lines=linesFrom(tokens),text=compact(lines.map(l=>l.text).join(" ")),score=(text.includes("最大積載量")?3:0)+(text.includes("使用者の氏名又は名称")?2:0)+(text.includes("総排気量又は定格出力")?2:0)+(text.includes("本自動車検査証発行時における所有者情報")?3:0);if(!best||score>best.score)best={tokens,lines,score,pageNumber:n};}const tokens=best?.tokens||[],lines=best?.lines||[];return{...recoverWeights(tokens,lines),...recoverIdentity(tokens,lines),...recoverOwnerAtIssuance(tokens,lines),...recoverDisplacement(tokens,lines),pageNumber:best?.pageNumber||1};}finally{await pdf.destroy?.().catch?.(()=>{});}}
export default function CertificatePdfSemanticRecovery(){useLayoutEffect(()=>{let dead=false,pending=null,latest=null,dispatching=false;const onChange=e=>{const input=e.target;if(!(input instanceof HTMLInputElement)||input.type!=="file")return;const file=input.files?.[0];if(!file||!(file.type==="application/pdf"||/\.pdf$/i.test(file.name||"")))return;const copy=file.slice(0,file.size,file.type);pending=extract(copy).then(r=>{if(!dead)latest=r;return r;}).catch(err=>{console.warn("certificate pdf semantic recovery",err);return null;});};const onAuth=async e=>{if(dispatching)return;const detail=e?.detail;if(!detail||typeof detail!=="object")return;const recovered=latest||(pending?await pending:null)||{};if(dead)return;const merged={...detail};for(const k of ["maxPayloadKg","vehicleWeightKg","grossVehicleWeightKg","maxPayloadRaw","maxPayloadPrimaryKg","maxPayloadAlternateKg","vehicleWeightRaw","vehicleWeightPrimaryKg","vehicleWeightAlternateKg","grossVehicleWeightRaw","grossVehicleWeightPrimaryKg","grossVehicleWeightAlternateKg","ownerNameRaw","ownerAddressRaw","userNameRaw","userAddressRaw","ownerAtIssuanceNameRaw","ownerAtIssuanceAddressRaw","displacementOrRatedOutput","displacementOrRatedOutputRaw","displacementOrRatedOutputValue","displacementOrRatedOutputUnit","__weightEvidence","__identityEvidence","__ownerAtIssuanceEvidence","__displacementEvidence"]){if(recovered[k]!==undefined&&recovered[k]!=="")merged[k]=recovered[k];}merged.automaticOwnerToUserResolution=false;const changed=JSON.stringify(merged)!==JSON.stringify(detail);if(!changed)return;dispatching=true;try{window[PDF_PRIORITY_KEY]=merged;window.dispatchEvent(new CustomEvent(AUTH_EVENT,{detail:merged}));}finally{dispatching=false;}};window.addEventListener("change",onChange,true);window.addEventListener(AUTH_EVENT,onAuth);return()=>{dead=true;window.removeEventListener("change",onChange,true);window.removeEventListener(AUTH_EVENT,onAuth);};},[]);return null;}
