"use client";

import { useLayoutEffect } from "react";
const AUTH_EVENT="vehicle-certificate-authoritative";
const PDF_PRIORITY_KEY="__vehicleCertificatePdfPriority";
function norm(v){return String(v??"").normalize("NFKC").replace(/[‐‑‒–—―]/g,"-").replace(/\r/g,"").replace(/[ \t]+/g," ").trim();}
function compact(v){return norm(v).replace(/[\s:：・,，()（）\[\]［］]/g,"");}
function makeToken(item,width,height){const text=norm(item?.str);if(!text)return null;const tr=item?.transform||[1,0,0,1,0,0];const x=Number(tr[4]||0)/Math.max(1,width),y=1-Number(tr[5]||0)/Math.max(1,height),w=Math.max(Number(item?.width||0),1)/Math.max(1,width),h=Math.max(Math.abs(Number(tr[3]||0)),Number(item?.height||0),1)/Math.max(1,height);return{text,x,y,w,h,cx:x+w/2};}
function linesFrom(tokens){const lines=[];for(const t of [...tokens].sort((a,b)=>a.y-b.y||a.x-b.x)){let line=lines.find(x=>Math.abs(x.y-t.y)<=Math.max(.0045,t.h*.72));if(!line){line={y:t.y,tokens:[]};lines.push(line);}line.tokens.push(t);line.y=line.tokens.reduce((s,x)=>s+x.y,0)/line.tokens.length;}for(const line of lines){line.tokens.sort((a,b)=>a.x-b.x);line.text=line.tokens.map(x=>x.text).join(" ");}return lines.sort((a,b)=>a.y-b.y);}
function anchor(lines,label){const wanted=compact(label);for(const line of lines)for(let s=0;s<line.tokens.length;s++){let joined="";for(let e=s;e<line.tokens.length&&e<s+16;e++){joined+=compact(line.tokens[e].text);if(joined.includes(wanted)){const first=line.tokens[s],last=line.tokens[e];return{line,y:line.y,left:first.x,right:last.x+last.w,cx:(first.x+last.x+last.w)/2};}if(joined.length>wanted.length+24)break;}}return null;}
function parseWeightText(text){const clean=norm(text).replace(/kg/ig," ");const m=clean.match(/(\d{3,5})(?:\s*[\[［]\s*(\d{3,5})\s*[\]］])?/);if(!m)return null;const primary=Number(m[1]),alternate=m[2]?Number(m[2]):null;if(!Number.isFinite(primary)||primary<300||primary>50000)return null;return{raw:alternate==null?String(primary):`${primary} [${alternate}]`,primary,alternate,source:clean};}
function parseWeightTokens(tokens){return parseWeightText([...tokens].sort((a,b)=>a.x-b.x).map(t=>t.text).join(" "));}
function recoverWeights(tokens,lines){
 const defs=[["最大積載量","maxPayloadKg","maxPayload"],["車両重量","vehicleWeightKg","vehicleWeight"],["車両総重量","grossVehicleWeightKg","grossVehicleWeight"]];
 const items=defs.map(([label,key,base])=>({label,key,base,a:anchor(lines,label)}));if(items.some(x=>!x.a))return{};
 const ordered=[...items].sort((a,b)=>a.a.cx-b.a.cx);const headerY=ordered.reduce((s,x)=>s+x.a.y,0)/ordered.length;
 const axleAnchors=["前前軸重","前後軸重","後前軸重","後後軸重"].map(x=>anchor(lines,x)).filter(Boolean);
 const structural=["前前軸重","長さ","幅","高さ","総排気量又は定格出力","型式","原動機の型式"].map(x=>anchor(lines,x)).filter(Boolean).filter(a=>a.y>headerY+.004);
 const bottom=structural.length?Math.min(...structural.map(a=>a.y))-.002:headerY+.09;
 const out={},evidence={};
 for(let i=0;i<ordered.length;i++){
  const item=ordered[i],prev=ordered[i-1]?.a,next=ordered[i+1]?.a;
  const left=prev?(prev.cx+item.a.cx)/2:Math.max(0,item.a.left-.055),right=next?(item.a.cx+next.cx)/2:Math.min(1,item.a.right+.09);
  const cellTokens=tokens.filter(t=>t.y>headerY+.001&&t.y<bottom&&t.cx>=left&&t.cx<right&&!/^(?:kg|cm|人)$/i.test(compact(t.text))&&!axleAnchors.some(a=>Math.abs(t.y-a.y)<.018));
  const byLine=lines.filter(l=>l.y>headerY+.001&&l.y<bottom).map(l=>({line:l,tokens:cellTokens.filter(t=>Math.abs(t.y-l.y)<Math.max(.005,t.h*.75))})).filter(x=>x.tokens.some(t=>/\d/.test(t.text)));
  let hit=null;for(const row of byLine){const parsed=parseWeightTokens(row.tokens);if(parsed){hit={...row,parsed};break;}}
  evidence[item.base]={label:item.label,labelX:item.a.cx,labelY:item.a.y,left,right,bottom,cellTokens:cellTokens.map(t=>({text:t.text,x:t.x,y:t.y,w:t.w,h:t.h})),selected:hit?{line:hit.line.text,parsed:hit.parsed}:null};
  if(!hit)continue;out[item.key]=hit.parsed.raw;out[`${item.base}Raw`]=hit.parsed.raw;out[`${item.base}PrimaryKg`]=hit.parsed.primary;out[`${item.base}AlternateKg`]=hit.parsed.alternate;
 }
 out.__weightEvidenceV3=evidence;return out;
}
function parseDecimalToken(text){const s=norm(text).replace(/,/g,".");const m=s.match(/^(\d{1,2})\s*[.．]\s*(\d{1,3})$/);if(m)return`${Number(m[1])}.${m[2]}`;if(/^\d{1,2}\.\d{1,3}$/.test(s))return s;return"";}
function recoverDisplacement(tokens,lines){const a=anchor(lines,"総排気量又は定格出力");if(!a)return{};const stops=["燃料の種類","型式指定番号","類別区分番号"].map(x=>anchor(lines,x)).filter(Boolean).filter(x=>x.y>a.y+.004);const bottom=stops.length?Math.min(...stops.map(x=>x.y))-.001:Math.min(1,a.y+.075);const region=tokens.filter(t=>t.y>a.y+.001&&t.y<bottom),values=[];for(const t of region){const v=parseDecimalToken(t.text);if(v)values.push({value:v,t});}for(const line of lines.filter(l=>l.y>a.y+.001&&l.y<bottom)){const joined=line.tokens.map(t=>norm(t.text)).join("");const v=parseDecimalToken(joined);if(v){const nums=line.tokens.filter(t=>/[\d.．]/.test(t.text));if(nums.length)values.push({value:v,t:{...nums[0],cx:nums.reduce((s,x)=>s+x.cx,0)/nums.length,y:line.y}});}}const units=region.filter(t=>/^(?:L|l|ℓ|kW|KW|kw)$/.test(compact(t.text)));let best=null;for(const v of values)for(const u of units){const dx=Math.abs(v.t.cx-u.cx),dy=Math.abs(v.t.y-u.y);if(dx>.09||dy>.035)continue;const score=dx+dy*2;if(!best||score<best.score)best={...v,u,score};}const sourceTokens=region.map(t=>t.text).join(" | ");if(!best)return{__displacementEvidenceV3:{sourceTokens,parsed:null}};const unit=/^(?:L|l|ℓ)$/.test(compact(best.u.text))?"L":"kW";return{displacementOrRatedOutput:`${best.value} ${unit}`,displacementOrRatedOutputRaw:`${best.value} ${norm(best.u.text)}`,displacementOrRatedOutputValue:best.value,displacementOrRatedOutputUnit:unit,__displacementEvidenceV3:{sourceTokens,parsed:{value:best.value,unit,valueX:best.t.cx,unitX:best.u.cx,valueY:best.t.y,unitY:best.u.y}}};}
async function extract(file){const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/legacy/build/pdf.worker.min.mjs",import.meta.url).toString();const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;try{let best=null;for(let n=1;n<=Math.min(pdf.numPages||1,8);n++){const page=await pdf.getPage(n),vp=page.getViewport({scale:1}),content=await page.getTextContent();const tokens=(content.items||[]).map(x=>makeToken(x,vp.width,vp.height)).filter(Boolean),lines=linesFrom(tokens),text=compact(lines.map(l=>l.text).join(" "));const score=(text.includes("最大積載量")?3:0)+(text.includes("車両重量")?2:0)+(text.includes("総排気量又は定格出力")?3:0);if(!best||score>best.score)best={tokens,lines,score};}return{...recoverWeights(best?.tokens||[],best?.lines||[]),...recoverDisplacement(best?.tokens||[],best?.lines||[])};}finally{await pdf.destroy?.().catch?.(()=>{});}}
export default function CertificatePdfWeightDisplacementRecovery(){useLayoutEffect(()=>{let dead=false,pending=null,latest=null,dispatching=false;const onChange=e=>{const input=e.target;if(!(input instanceof HTMLInputElement)||input.type!=="file")return;const file=input.files?.[0];if(!file||!(file.type==="application/pdf"||/\.pdf$/i.test(file.name||"")))return;const copy=file.slice(0,file.size,file.type);pending=extract(copy).then(r=>{if(!dead)latest=r;return r;}).catch(err=>{console.warn("certificate weight/displacement recovery",err);return null;});};const onAuth=async e=>{if(dispatching)return;const detail=e?.detail;if(!detail||typeof detail!=="object")return;const recovered=latest||(pending?await pending:null)||{};if(dead)return;const merged={...detail};const keys=["maxPayloadKg","vehicleWeightKg","grossVehicleWeightKg","maxPayloadRaw","maxPayloadPrimaryKg","maxPayloadAlternateKg","vehicleWeightRaw","vehicleWeightPrimaryKg","vehicleWeightAlternateKg","grossVehicleWeightRaw","grossVehicleWeightPrimaryKg","grossVehicleWeightAlternateKg","displacementOrRatedOutput","displacementOrRatedOutputRaw","displacementOrRatedOutputValue","displacementOrRatedOutputUnit","__weightEvidenceV3","__displacementEvidenceV3"];for(const key of keys)if(recovered[key]!==undefined&&recovered[key]!=="")merged[key]=recovered[key];if(JSON.stringify(merged)===JSON.stringify(detail))return;dispatching=true;try{window[PDF_PRIORITY_KEY]=merged;window.dispatchEvent(new CustomEvent(AUTH_EVENT,{detail:merged}));}finally{dispatching=false;}};window.addEventListener("change",onChange,true);window.addEventListener(AUTH_EVENT,onAuth);return()=>{dead=true;window.removeEventListener("change",onChange,true);window.removeEventListener(AUTH_EVENT,onAuth);};},[]);return null;}
