"use client";

import { PointerEvent, useRef, useState } from "react";

type Band={rowIndex:number;y1Norm:number;y2Norm:number;y1Px:number;y2Px:number};
type Photo={fileName:string;file:File;url:string;width:number;height:number;rotationDeg:number;bands:Band[]};
const s:any={page:{maxWidth:900,margin:"0 auto",padding:"16px 12px 60px",background:"#f5f7fb",minHeight:"100vh",color:"#172033"},card:{background:"#fff",border:"1px solid #dbe2ec",borderRadius:16,padding:14,marginBottom:12},primary:{width:"100%",border:0,borderRadius:13,padding:"14px 12px",background:"#2468df",color:"#fff",fontWeight:800,fontSize:17},secondary:{border:"1px solid #ccd5e3",borderRadius:11,padding:"10px 12px",background:"#fff",fontWeight:800},text:{fontSize:14,color:"#5b6678",lineHeight:1.6}};
const clamp=(v:number)=>Math.max(0,Math.min(1,v));
const band=(a:number,b:number,h:number,i:number):Band=>({rowIndex:i,y1Norm:+Math.min(a,b).toFixed(6),y2Norm:+Math.max(a,b).toFixed(6),y1Px:Math.round(Math.min(a,b)*h),y2Px:Math.round(Math.max(a,b)*h)});
function load(file:File){return new Promise<HTMLImageElement>((res,rej)=>{const u=URL.createObjectURL(file),i=new Image();i.onload=()=>{URL.revokeObjectURL(u);res(i)};i.onerror=()=>rej(new Error(file.name));i.src=u})}
async function rotatePreview(file:File,deg:number){const i=await load(file);const d=((deg%360)+360)%360;if(!d)return{url:URL.createObjectURL(file),width:i.naturalWidth,height:i.naturalHeight};const swap=d===90||d===270,c=document.createElement("canvas");c.width=swap?i.naturalHeight:i.naturalWidth;c.height=swap?i.naturalWidth:i.naturalHeight;const x=c.getContext("2d")!;x.translate(c.width/2,c.height/2);x.rotate(d*Math.PI/180);x.drawImage(i,-i.naturalWidth/2,-i.naturalHeight/2);const b=await new Promise<Blob>((r,j)=>c.toBlob(v=>v?r(v):j(new Error("rotate")),"image/jpeg",.96));return{url:URL.createObjectURL(b),width:c.width,height:c.height}}
async function copy(t:string){try{await navigator.clipboard.writeText(t)}catch{const a=document.createElement("textarea");a.value=t;document.body.appendChild(a);a.select();document.execCommand("copy");a.remove()}}
export default function Page(){const fi=useRef<HTMLInputElement>(null),box=useRef<HTMLDivElement>(null);const[photos,setPhotos]=useState<Photo[]>([]),[cur,setCur]=useState(0),[start,setStart]=useState<number|null>(null),[draft,setDraft]=useState<number|null>(null),[msg,setMsg]=useState("");const p=photos[cur];
async function choose(files:FileList|null){if(!files?.length)return;photos.forEach(v=>URL.revokeObjectURL(v.url));const out:Photo[]=[];for(const f of Array.from(files)){const i=await load(f);out.push({fileName:f.name,file:f,url:URL.createObjectURL(f),width:i.naturalWidth,height:i.naturalHeight,rotationDeg:0,bands:[]})}setPhotos(out);setCur(0);setMsg(`${out.length}枚読み込み。各画像の実明細行を縦bandで指定してください。`)}
function y(e:PointerEvent<HTMLDivElement>){const r=box.current?.getBoundingClientRect();return r?.height?clamp((e.clientY-r.top)/r.height):null}
function down(e:PointerEvent<HTMLDivElement>){const v=y(e);if(v==null)return;e.currentTarget.setPointerCapture(e.pointerId);setStart(v);setDraft(v)}function move(e:PointerEvent<HTMLDivElement>){if(start==null)return;const v=y(e);if(v!=null)setDraft(v)}function up(e:PointerEvent<HTMLDivElement>){if(!p||start==null)return;const end=y(e)??draft??start;if(Math.abs(end-start)>=8/Math.max(1,p.height))setPhotos(old=>old.map((q,i)=>i!==cur?q:{...q,bands:[...q.bands,band(start,end,q.height,q.bands.length+1)].sort((a,b)=>a.y1Norm-b.y1Norm).map((v,j)=>band(v.y1Norm,v.y2Norm,q.height,j+1))}));setStart(null);setDraft(null)}
async function rot(){if(!p)return;const d=(p.rotationDeg+90)%360,r=await rotatePreview(p.file,d);URL.revokeObjectURL(p.url);setPhotos(old=>old.map((q,i)=>i===cur?{...q,...r,rotationDeg:d,bands:[]}:q))}
const payload={schema:"icb.parts-ocr.row-gt.v1",variant:"additional-yellow-real",evaluationSet:"additional-yellow-real",images:photos.map(q=>({fileName:q.fileName,imageWidth:q.width,imageHeight:q.height,rotationDeg:q.rotationDeg,rowCount:q.bands.length,rows:q.bands}))};const ready=photos.length>0&&photos.every(q=>q.bands.length>0);
return <main style={s.page}><section style={s.card}><h1 style={{margin:0}}>Stage A18 Additional Yellow Row GT</h1><p style={s.text}>追加黄色伝票用。OCR結果は表示せず、元写真だけを見て実明細行を指定します。画像・GTはブラウザ内のみで扱い、GitHub/サーバーへ保存しません。</p><input ref={fi} hidden type="file" accept="image/*" multiple onChange={e=>void choose(e.target.files)}/><button style={s.primary} onClick={()=>fi.current?.click()}>追加黄色伝票の写真を選択</button><p style={s.text}>{msg}</p></section>{p&&<><section style={s.card}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center"}}><button style={s.secondary} disabled={cur===0} onClick={()=>setCur(v=>v-1)}>←前</button><strong>{cur+1}/{photos.length} {p.fileName}</strong><button style={s.secondary} disabled={cur===photos.length-1} onClick={()=>setCur(v=>v+1)}>次→</button></div><div style={{display:"flex",gap:8,margin:"10px 0"}}><button style={s.secondary} onClick={()=>void rot()}>90°回転</button><button style={s.secondary} onClick={()=>setPhotos(o=>o.map((q,i)=>i===cur?{...q,bands:q.bands.slice(0,-1)}:q))}>1つ戻す</button><button style={s.secondary} onClick={()=>setPhotos(o=>o.map((q,i)=>i===cur?{...q,bands:[]}:q))}>全消去</button></div><div ref={box} style={{position:"relative",touchAction:"none",userSelect:"none"}} onPointerDown={down} onPointerMove={move} onPointerUp={up}><img src={p.url} style={{display:"block",width:"100%",height:"auto"}} alt="GT"/>{p.bands.map(b=><div key={b.rowIndex} style={{position:"absolute",left:0,right:0,top:`${b.y1Norm*100}%`,height:`${(b.y2Norm-b.y1Norm)*100}%`,border:"2px solid #e33",background:"rgba(255,0,0,.09)",pointerEvents:"none"}}/>)}{start!=null&&draft!=null&&<div style={{position:"absolute",left:0,right:0,top:`${Math.min(start,draft)*100}%`,height:`${Math.abs(draft-start)*100}%`,border:"2px dashed #2468df",pointerEvents:"none"}}/>}</div><p style={s.text}>この画像のGT行数：{p.bands.length}</p></section><section style={s.card}><button disabled={!ready} style={{...s.primary,opacity:ready?1:.5}} onClick={async()=>{await copy(JSON.stringify(payload,null,2));setMsg("Row GT JSONをコピーしました。Stage A18評価画面へ貼り付けてください。")}}>Row GT JSONをコピー</button></section></>}</main>}
