/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useRef, useState } from "react";
import { detectPaperBox, getA19DynamicRows, orientedCanvas } from "../stage-a20/a19-table-crops";
import { FORMAL_A19_GT } from "../stage-a20/formal-gt";
import { recognizeOnnx, recognizeTess, type FieldKey } from "../stage-a20/recognition";
import { analyzeCellCrop } from "../stage-a21/crop-diagnostics";
import { resolveTarget0684 } from "../stage-a21/RealImageAudit";
import { attributeNormalization, classifyNormalization, columnsFromMeasuredRules, makeA22CellCrop, measureTableRules, rectifyPaper, refineRowsByRules } from "./crop-correction";

const FIELDS:FieldKey[]=["name","qty","retail","cost"];
const ENGINES=["CONTROL_TESS","ONNX_JA_LIGHT","ONNX_V5"] as const;
type EngineKey=typeof ENGINES[number];
type Row={name:string;qty:string;retail:string;cost:string};
const norm=(v:string)=>v.normalize("NFKC").replace(/[￥¥,\s]/g,"").toUpperCase();
function score(gt:Row[],pred:Row[]){let correct=0,blank=0,misread=0,complete=0;const byField:any=Object.fromEntries(FIELDS.map(f=>[f,{correct:0,total:gt.length}]));for(let i=0;i<gt.length;i++){const p=pred[i]||{name:"",qty:"",retail:"",cost:""};let ok=true;for(const f of FIELDS){const a=norm(gt[i]?.[f]||""),b=norm(p[f]||"");if(a&&a===b){correct++;byField[f].correct++;}else{ok=false;if(!b)blank++;else misread++;}}if(ok)complete++;}return{correct,total:gt.length*4,complete,blank,misread,byField};}
function compact(result:any){const cells=result.cells||[],trunc=cells.filter((c:any)=>c.crop.truncationLikely).length,lines=cells.filter((c:any)=>c.crop.tableLineLikely).length,lowOcc=cells.filter((c:any)=>(c.crop.darkOccupancy??1)<.0025).length,edge=cells.filter((c:any)=>Object.values(c.crop.edgeTouch||{}).some(Boolean)).length;const engines=ENGINES.map(e=>{const s=result.methods[e],destructive=cells.filter((c:any)=>c.recognition[e]?.normalizationAttribution==="normalization-destructive-candidate").length,cropBeforeNorm=cells.filter((c:any)=>c.recognition[e]?.normalizationAttribution==="crop-contamination-before-normalization").length,policyReject=cells.filter((c:any)=>c.recognition[e]?.normalizationClass==="numeric-policy-rejected-no-digit").length;return `${e}: ${s.correct}/${s.total}, complete ${s.complete}/${result.gtRows}, blank ${s.blank}, misread ${s.misread}, trueNormCandidate ${destructive}, cropBeforeNorm ${cropBeforeNorm}, numericPolicyReject ${policyReject}`;}).join("\n");const primary=trunc>cells.length*.25||lines>cells.length*.35||lowOcc>cells.length*.25?"CELL_CROP_QUALITY STILL PRIMARY":"CROP STRUCTURE IMPROVED; RECOGNIZER/EXTRACTION NEXT";return `【Stage A22 targeted diagnostic】\ntarget: IMG_0684\nevalHead: ${result.deployedHead}\nGT: scoring-only / runtime use false\nGT rows: ${result.gtRows} / dynamic rows: ${result.dynamicRows}\nrectification: projective ${result.rectification.projectiveApplied} / skew ${result.rectification.skewDeg.toFixed(2)}deg / perspective ${result.rectification.perspectiveDelta.toFixed(4)} / quadConf ${result.rectification.quadConfidence.toFixed(3)}\nrules: H ${result.rules.horizontalCount} / V ${result.rules.verticalCount}\nrule-bounded rows: ${result.ruleBoundedRows}/${result.dynamicRows}\ncell diagnostics: truncation ${trunc}/${cells.length}, table-line ${lines}/${cells.length}, lowOccupancy ${lowOcc}/${cells.length}, edgeTouch ${edge}/${cells.length}\n${engines}\n主原因判定: ${primary}\nA22 changes: projective rectification + measured table-rule bands + nearest-rule row reconstruction + monotonic unique column assignment + line exclusion margin + white OCR padding\nmodel swap: none\nA17/A19 threshold micro-tuning: none`;}

export default function RealImageAudit({deployedHead}:{deployedHead:string}){
 const input=useRef<HTMLInputElement>(null);const[busy,setBusy]=useState(false);const[status,setStatus]=useState("正式12枚を一括選択してください。対象は自動識別します。");const[result,setResult]=useState<any>(null);
 async function run(list:FileList|null){if(!list)return;const files=Array.from(list),resolved=resolveTarget0684(files);if(!resolved.target){setStatus(`STOP：正式12枚mapping不成立（${resolved.reason}）。手動判別は要求しません。`);return;}const file=resolved.target,gt=FORMAL_A19_GT["IMG_0684(1)"] as Row[];setBusy(true);setResult(null);let worker:any=null;try{const tess:any=await import("tesseract.js");worker=await tess.createWorker("jpn+eng",1);setStatus("対象画像を自動識別しました。A22 structural crop診断中…");const original=await orientedCanvas(file),paper0=detectPaperBox(original.canvas),rect=rectifyPaper(original.canvas,paper0);const correctedFile=await new Promise<File>((resolve,reject)=>rect.canvas.toBlob(b=>b?resolve(new File([b],"IMG_0684-a22.jpg",{type:"image/jpeg"})):reject(new Error("rectified blob failed")),"image/jpeg",.96)),correctedColor={canvas:rect.canvas,rotate:false},dynamic=await getA19DynamicRows(worker,tess,correctedFile,correctedColor,rect.paper),rules=measureTableRules(rect.canvas,rect.paper),rows=refineRowsByRules(dynamic.rows,rules,rect.paper),cols=columnsFromMeasuredRules(rules,rect.paper),rowsByEngine:Record<EngineKey,Row[]>={CONTROL_TESS:[],ONNX_JA_LIGHT:[],ONNX_V5:[]},cells:any[]=[];
 for(let r=0;r<rows.length;r++){const out:any={CONTROL_TESS:{name:"",qty:"",retail:"",cost:""},ONNX_JA_LIGHT:{name:"",qty:"",retail:"",cost:""},ONNX_V5:{name:"",qty:"",retail:"",cost:""}};for(const field of FIELDS){const cell=await makeA22CellCrop(rect.canvas,rect.paper,rows[r],cols[field],field,r,field==="name"?1600:900),crop=analyzeCellCrop(cell.canvas),rec:any={};const tr=await recognizeTess(worker,tess,cell.blob,field);rec.CONTROL_TESS={...tr,normalizationClass:classifyNormalization(tr.raw,tr.normalized,field),normalizationAttribution:attributeNormalization(tr.raw,tr.normalized,field,crop)};out.CONTROL_TESS[field]=tr.normalized;for(const e of ["ONNX_JA_LIGHT","ONNX_V5"] as const){try{const rr=await recognizeOnnx(e,cell.canvas,field);rec[e]={...rr,normalizationClass:classifyNormalization(rr.raw,rr.normalized,field),normalizationAttribution:attributeNormalization(rr.raw,rr.normalized,field,crop)};out[e][field]=rr.normalized;}catch(err:any){rec[e]={raw:"",normalized:"",confidence:null,error:String(err?.message||err),normalizationClass:"error",normalizationAttribution:"error"};}}cells.push({rowIndex:r,field,row:{top:rows[r].top,bottom:rows[r].bottom,center:rows[r].center,boundedByRules:rows[r].boundedByRules,sourceRowIndex:r},column:cols[field],crop:{preview:cell.preview,padding:cell.padding,...crop},recognition:rec});}for(const e of ENGINES)rowsByEngine[e].push(out[e]);}
 const summary={schema:"icb.parts-ocr.stage-a22-targeted-crop-correction.v2",deployedHead,targetBaseId:"0684",gtRuntimeUse:false,gtScoringOnly:true,recognitionParametersChanged:false,a17A19ThresholdsChanged:false,rowSlotsCompacted:false,gtRows:gt.length,dynamicRows:dynamic.rows.length,ruleBoundedRows:rows.filter(r=>r.boundedByRules).length,rectification:{skewDeg:rect.skewDeg,perspectiveDelta:rect.perspectiveDelta,quadConfidence:rect.quad.confidence,projectiveApplied:rect.projectiveApplied},rules:{horizontalCount:rules.horizontal.length,verticalCount:rules.vertical.length,horizontalThickness:rules.horizontalThickness,verticalThickness:rules.verticalThickness},methods:Object.fromEntries(ENGINES.map(e=>[e,score(gt,rowsByEngine[e])])),cells};setResult(summary);setStatus("A22 targeted diagnostic完了。browser-onlyです。");}catch(e:any){setStatus(`ERROR: ${String(e?.message||e)}`);}finally{if(worker)await worker.terminate().catch(()=>{});setBusy(false);if(input.current)input.current.value="";}}
 async function copyShort(){if(!result)return;await navigator.clipboard.writeText(compact(result));setStatus("総合管理用短縮summaryをコピーしました。");}
 async function copyJson(){if(!result)return;await navigator.clipboard.writeText(JSON.stringify(result));setStatus("詳細JSONをコピーしました。");}
 return <section style={{background:"#fff",border:"1px solid #dbe2ec",borderRadius:16,padding:14}}><h2>Stage A22 targeted corrected-crop diagnostic</h2><p>正式黄色12枚を一括選択すると、IMG_0684を自動識別してA22補正cropだけを診断します。</p><input ref={input} hidden multiple type="file" accept="image/*" onChange={e=>run(e.target.files)}/><button disabled={busy} onClick={()=>input.current?.click()} style={{width:"100%",padding:12,border:0,borderRadius:12,fontWeight:800}}>{busy?"診断中…":"正式12枚を選択してください"}</button><div style={{marginTop:8,fontSize:13}}>{status}</div>{result&&<><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:10}}><button onClick={copyShort}>総合管理用短縮summaryをコピー</button><button onClick={copyJson}>詳細JSONをコピー</button></div><div style={{marginTop:10,fontSize:12}}>projective {String(result.rectification.projectiveApplied)} / skew {result.rectification.skewDeg.toFixed(2)}° / perspective {result.rectification.perspectiveDelta.toFixed(4)} / rules H{result.rules.horizontalCount} V{result.rules.verticalCount} / rule-bounded {result.ruleBoundedRows}/{result.dynamicRows}</div></>}</section>;
}
